[programs.localnet]
pool-mint = "6cDMc7baVfghT4sUx1t3sEfohxXyj4XwDr8pbarQfz1z"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
