[package]
name = "pool-mint"
version = "0.1.0"
description = "Main pool-mint Lib"
edition = "2018"

[lib]
crate-type = ["cdylib", "lib"]
name = "pool_mint"

[features]
no-entrypoint = []
no-idl = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = "0.18.2"
anchor-spl = "0.18.2"